# configs/EEGNet.yaml
model:
  name: EEGNet
  params:
    F1:              8         # Number of filters in the first conv layer
    D:               2         # Depth multiplier
    F2:              16        # Number of filters in the separable conv (pointwise) layer
    kernel_size_1:   [1, 160]  # Temporal kernel (~1.25 s @ 128 Hz)
    kernel_size_2:   [32, 1]   # Depthwise spatial kernel
    kernel_size_3:   [1, 16]   # Separable depthwise temporal kernel
    pooling_size_1:  [1, 4]    # First temporal downsampling
    pooling_size_2:  [1, 8]    # Second temporal downsampling
    dropout_rate:    0.5
    signal_length:   640       # Input window length (samples)
    num_class:       4         # Number of classes

data:
  data_root: "/data2/wyxuan/DataSet"
  session: 1
  channels_sel: [9,10,11,12,13,14,17,18,19,20,21,22,
                 44,45,46,49,50,51,54,55,56,57,58,59,25,26,30,63,62,27,29,64]
  highpass: 0.5
  lowpass: 5.0
  filter_order: 4

training:
  epochs: 100
  batch_size: 256
  val_n_subjects: 10
  patience: 10

  # optimizer:
  #   name: "SGD"
  #   params:
  #     lr: 0.001
  #     momentum: 0.9
  #     weight_decay: 0.0001

  optimizer:
    name: "AdamW"
    params:
      lr: 0.001
      weight_decay: 0.001

  bootstrap:
    enabled: False      # Enable bootstrap augmentation
    sample_size: 5      # Each synthetic sample is the average of 5 trials from the same class
    num_augment: 100    # Number of augmented samples per class

tsne:
  enable: true
  subjects: [1,2,3,4,5,6,7,8,9,10,
             11,12,13,14,15,16,17,18,19,20,
             21,22,23,24,25,26,27,28,29,30]  # Optional; omit to use test_ids

device: "cuda:1"
