model:
  name: MTSNet
  params:
    C: 32                  # 通道数
    T: 640                 # 采样点长度
    N: 4                   # 类别数
    depth_L: 2             # 时域分支层数
    depth_M: 1             # 融合分支层数
    kernal_length: 127    # 卷积核长度（对应 1Hz 周期≈128点）
    dropout: 0.5

data:
  data_root: "/data2/wyxuan/DataSet"
  session: 1
  channels_sel: [9,10,11,12,13,14,17,18,19,20,21,22,
                 44,45,46,49,50,51,54,55,56,57,58,59,25,26,30,63,62,27,29,64]
  highpass: 0.5
  lowpass: 5.0
  filter_order: 4

training:
  epochs: 100
  batch_size: 256
  val_n_subjects: 14
  patience: 5

  optimizer:
    name: "SGD"
    params:
      lr: 0.001
      momentum: 0.9
      weight_decay: 0.0001

  # optimizer:
  #   name: "Adam"
  #   params:
  #     lr: 0.001
  #     weight_decay: 0.001

  bootstrap:
    enabled: True      # 是否开启
    sample_size: 5       # 每个新样本由 5 条同类 trial 平均得到
    num_augment: 100      # 每个类别生成 20 个增强样本

device: "cuda:3" 