# configs/SSVEPFormer.yaml
model:
  name: SSVEPFormer
  params:
    C: 32
    T: 640
    N: 4
    fs: 128
    freq_range: [0.5, 5]
    dropout: 0.5

data:
  data_root: "D:/14-AORIonline/DataSet"
  session: 1
  channels_sel: [9,10,11,12,13,14,17,18,19,20,21,22,
                 44,45,46,49,50,51,54,55,56,57,58,59,25,26,30,63,62,27,29,64]
  highpass: 0.5
  lowpass: 5.0
  filter_order: 4

training:
  epochs: 100
  batch_size: 256
  val_n_subjects: 9
  patience: 5

  optimizer:
    name: "SGD"
    params:
      lr: 0.001
      momentum: 0.9
      weight_decay: 0.0001

device: "cuda" 
