# configs/TimeFormer.yaml
model:
  name: TimeFormer
  params:
    C: 32
    T: 640
    N: 4
    fs: 128
    freq_range: [0.5, 5]
    dropout: 0.5

data:
  data_root: "/data2/wyxuan/DataSet"
  session: 1
  channels_sel: [9,10,11,12,13,14,17,18,19,20,21,22,
                 44,45,46,49,50,51,54,55,56,57,58,59,25,26,30,63,62,27,29,64]
  highpass: 0.5
  lowpass: 5.0
  filter_order: 4

training:
  epochs: 100
  batch_size: 256
  val_n_subjects: 8
  patience: 10
  adv_lambda: 0.1

  # optimizer:
  #   name: "SGD"
  #   params:
  #     lr: 0.001
  #     momentum: 0.9
  #     weight_decay: 0.0001

  optimizer:
    name: "AdamW"
    params:
      lr: 0.001
      weight_decay: 0.001

device: "cuda:1" 
